# Generated by Django 3.0.2 on 2020-01-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
    ]
