# Generated by Django 3.0.2 on 2020-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_cover.jpg', upload_to='cover_pics'),
        ),
    ]
