# Generated by Django 3.0.2 on 2020-01-30 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookclub.Notes'),
        ),
    ]
