# Generated by Django 3.0.2 on 2020-01-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0006_auto_20200130_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookclub.Notes'),
        ),
    ]
