# Generated by Django 3.0.2 on 2020-01-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0008_auto_20200130_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
