# Generated by Django 3.0.2 on 2020-02-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0016_auto_20200204_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='date',
        ),
    ]
